# Generated by Django 4.0.6 on 2022-09-01 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bus_admin', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bus_admin.subroute'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_begin_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bus_admin.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
