# Generated by Django 4.0.6 on 2022-09-08 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_remove_booking_seat_booking_seat_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='traveler_contact',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+251......'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
    ]
