# Generated by Django 4.0.6 on 2022-09-08 14:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_booking_traveler_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='traveler_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
