# Generated by Django 4.0.6 on 2022-09-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishPayment',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finishpymnt_booking', serialize=False, to='Customer.booking')),
                ('paid_by', models.CharField(max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=55)),
                ('account_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishPaymentStatus',
            fields=[
                ('fnishpayment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finishpayment_status', serialize=False, to='Booker.finishpayment')),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
