# Generated by Django 4.0.6 on 2022-08-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('System_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('type', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('shortCode', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('start', models.CharField(max_length=255, null=True)),
                ('destnation', models.CharField(max_length=255, null=True)),
                ('via_cities', models.CharField(max_length=255, null=True)),
                ('travel_distance', models.IntegerField()),
                ('travel_aproximate_time', models.CharField(max_length=255, null=True)),
                ('travel_date', models.DateField()),
                ('travel_begin_time', models.TimeField()),
                ('travel_facilities', models.CharField(max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_bus', to='System_admin.bus')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=55)),
                ('account_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pymentmethod', models.ManyToManyField(to='Booker.paymentmethod')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booker.route')),
            ],
        ),
    ]
