# Generated by Django 4.0.6 on 2022-09-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_booking_destination_booking_start_booking_sub_route_and_more'),
        ('Bus_admin', '0001_initial'),
        ('Booker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishPayment',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finishpymnt_booking', serialize=False, to='Customer.booking')),
                ('paid_by', models.CharField(max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='shortCode',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='paymentinformantion',
            name='pymentmethod',
        ),
        migrations.AddField(
            model_name='paymentinformantion',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booker.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymentinformantion',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus_admin.route'),
        ),
        migrations.CreateModel(
            name='FinishPaymentStatus',
            fields=[
                ('fnishpayment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finishpayment_status', serialize=False, to='Booker.finishpayment')),
                ('status', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='finishpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booker.paymentinformantion'),
        ),
    ]
