# Generated by Django 4.0.6 on 2022-09-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_admin', '0003_paymentmethod'),
        ('Booker', '0002_finishpayment_rename_shortcode_paymentmethod_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformantion',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System_admin.paymentmethod'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
