# Generated by Django 4.0.6 on 2022-09-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_remove_booking_seat_booking_seat_quantity'),
        ('Booker', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignSeat',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assign_seat', serialize=False, to='Customer.booking')),
                ('seat_number', models.IntegerField()),
            ],
        ),
    ]
