# Generated by Django 4.0.6 on 2022-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0003_assignseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignseat',
            name='seat_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
