# Generated by Django 4.0.6 on 2022-09-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_admin', '0001_initial'),
        ('System_admin', '0003_paymentmethod'),
        ('Booker', '0003_alter_paymentinformantion_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentInformantion',
            new_name='PaymentInformation',
        ),
    ]
