# Generated by Django 4.0.6 on 2022-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0004_alter_assignseat_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishpayment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
