# Generated by Django 4.0.6 on 2022-09-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0005_finishpayment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishpayment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booker.paymentinformation'),
        ),
        migrations.AlterField(
            model_name='finishpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
