# Generated by Django 4.0.6 on 2022-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booker', '0006_alter_finishpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishpayment',
            name='screenshot',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
