# Generated by Django 4.0.6 on 2022-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_admin', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_bus',
            name='plate_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
