# Generated by Django 4.0.6 on 2022-09-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_admin', '0004_remove_subroute_subroute_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subroutebusadmin',
            name='subroute_bus',
        ),
        migrations.RemoveField(
            model_name='subroutebusadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubRouteAdmin',
        ),
        migrations.DeleteModel(
            name='SubRouteBusAdmin',
        ),
    ]
