# Generated by Django 4.0.6 on 2022-08-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
