# Generated by Django 4.0.6 on 2022-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
