# Generated by Django 4.0.6 on 2022-09-01 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_type',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_number',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='number_of_seats',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='number_of_buses',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BusAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='System_admin.bus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
