# Generated by Django 4.0.6 on 2022-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='about',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='logo',
            field=models.ImageField(max_length=55, null=True, upload_to=''),
        ),
    ]
