# Generated by Django 4.0.6 on 2022-09-03 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('System_admin', '0003_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
